const sampleListings = [
  {
    vname: "Maruti Suzuki Grand Vitara 2024",
    vtype:"electric_car",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"The 2024 Suzuki Grand Vitara is a compact SUV with hybrid options. It is petrol-automatic with mileage varriying frpm 24-27 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://media.istockphoto.com/id/481177156/photo/suzuki-vitara-on-the-road.jpg?s=1024x1024&w=is&k=20&c=9Ut0JqfEsJHCdJF2ZNXBtvx72gsUgZ5pIqnKGOtV17w=",
    },
    cost: 1500,
    location: "XY-kha Vikas Nagar, Tedhi Pulia, Lucknow, 248198",
    city:"Lucknow",
    state: "Uttar Pradesh",
  },
  {
    vname: "Maruti Suzuki Swift 2024",
    vtype:"car",
    vfuel:"Deisel",
    vlimit:"100",
    vpower:"1200",
    vinfo:"The Swift is known for its bold and sporty design, featuring a sloping roofline. It is deisel based 1298cc engine with mileage around 23-27 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://images.pexels.com/photos/18316714/pexels-photo-18316714/free-photo-of-newlyweds-standing-by-red-suzuki-swift.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    },
    cost: 1200,
    location: "XZ-kha near V-Mart Alambagh",
    city:"Patna",
    state: "Bihar",
  },
  {
    vname: "TVS Apache 160 2022",
    vtype:"bike",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"The TVS Apache 160cc is a sporty motorcycle with a 159.7cc engine, 16.5 bhp, 5-speed gearbox, and optional ABS. It's mileage is around 60 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://www.jansatta.com/wp-content/uploads/2023/02/TVS-Apache-RTR-160.jpg",
    },
    cost: 1000,
    location: "XYZ near Jankipuram Hospital, Bakshi ka Talab",
    city:"Lucknow",
    state: "UP",
  },
  {
    vname: "Mahindra XUV 300",
    vtype:"electric_bike",
    vfuel:"Petrol",
    vlimit:"97",
    vpower:"1200",
    vinfo:"The front grille, sleek projector headlamps, and LED DRLs give it a dynamic look. It's mileage is around 15-18kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse4.mm.bing.net/th?id=OIP.IaU3ULoZKc5D0rrdKSr2FwHaFj&pid=Api&P=0&h=180",
    },
    cost: 2500,
    location: "XYZ near Smart Mart, LalBagh",
    city:"Lucknow",
    state: "Punjab",
  },
  {
    vname: "Maruti Suzuki Swift Desire",
    vtype:"car",
    vfuel:"Deisel",
    vlimit:"100",
    vpower:"1200",
    vinfo:"The Dzire has a sleek and modern design with a wide front grille, LED projector headlamps, and DRLs. It's Mileage is around 20-23 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse3.mm.bing.net/th?id=OIP.1gCycGoTsCnhYgURcmzLdgHaD4&pid=Api&P=0&h=180",
    },
    cost: 800,
    location: "AAA near railway station, Bakshi Ka Talab",
    city:"Lucknow",
    state: "Odisha",
  },
  {
    vname: "Tata Punch 2024",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"90",
    vpower:"1200",
    vinfo:"Powered by a 1.2L Revotron petrol engine with manual and AMT transmission options. It also complies with BS6 Phase II norms. It's mileage is arounnd 17-21 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://motoroctane.com/wp-content/uploads/2022/04/Tata-Punch-EV.jpg",
    },
    cost: 2000,
    location: "AXD near SBI, Aliganj",
    city:"Lucknow",
    state: "Rajsthan",
  },
  {
    vname: "Hero Splendor 2022",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"It features a simple design, a 97.2cc engine, and offers a mileage of around 65–70 km/l. Ideal for daily use, it remains a top choice for budget-conscious riders.",
    image:{
      filename: "Listingimage",
      url: "https://autoflee.com/wp-content/uploads/2022/09/cover-3.png",
    },
    cost: 900,
    location: "WWW near V-Mart, Charbagh",
    city:"Lucknow",
    state:"West Bangal",
  },
  {
    vname: "Tata Harrier",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"90",
    vpower:"1200",
    vinfo:"Powered by a 2.0-liter Kryotec diesel engine delivering 170 PS of power and 350 Nm of torque. It's mileage is around 14-18kmpl",
    image:{
      filename: "Listingimage",
      url: "https://preview.free3d.com/img/2019/04/2400323714378892518/8u8ji8ym.jpg",
    },
    cost: 3500,
    location: "QWE near Shaheed Path, Gol City 226025",
    city:"Lucknow",
    state: "Madhya Pradesh",
  },
  {
    vname: "Maruti Suzuki Baleno",
    vtype:"car",
    vfuel:"Deisel",
    vlimit:"95",
    vpower:"1200",
    vinfo:"It has gained immense popularity for its stylish design, excellent fuel efficiency, and advanced features. The Baleno is designed for those seeking a sleek, fuel-efficient, and feature-packed car. It's mileage is around 22-24 kmpl.",
    image:{
      filename: "Listingimage",
      url: "https://stat.overdrive.in/wp-content/odgallery/2016/01/28131_DSC_7736.JPG",
    },
    cost: 3000,
    location: "AAX near Shyam Eye Hospital 422001 ",
    city:"Lucknow",
    state: "Andhra Pradesh",
  },
  {
    vname: "Mahindra Thar 2023",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"A perfect blend of adventure and comfort, the Thar appeals to off-road enthusiasts and city drivers alike. It is petrol-automatic engine and mileage around 7-11 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://images.carandbike.com/cms/static-content/296/articles/3205353/Mahindra_Thar_2_WD_24_2023_01_08_T07_39_39_947_Z_2937ce8903.jpg",
    },
    cost: 4000,
    location: "AAE near New Colony Deoria 274001",
    city:"Lucknow",
    state: "Himanchal Pradesh",
  },
  {
    vname: "Royal  Enfield Bulllet 350 Classic",
    vtype:"bike",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"Retains its timeless, retro design with a teardrop fuel tank, classic round headlamp, and pinstriping. It's mileage is around 35-40kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse2.mm.bing.net/th?id=OIP.4Alf4XHPGV0wrvGsFugJtgHaD2&pid=Api&P=0&h=180",
    },
    cost: 1800,
    location: "WER near City Hospital Building no.312, 261201",
    city:"Lucknow",
    state: "Chhattisgarh",
  },
  {
    vname: "Hyundai Creta",
    vtype:"car",
    vfuel:"Deisel",
    vlimit:"80",
    vpower:"1200",
    vinfo:"Available with both 6-speed manual and CVT/7-speed DCT transmission options depending on the variant. It's mileage is around 18-22 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://www.livemint.com/lm-img/img/2024/01/15/1600x900/creta_facelift_1705325386381_1705325392269.jpg",
    },
    cost: 10000,
    location: "AAO near Buddha College, Kushinagar 274403",
    city:"Lucknow",
    state: "Hariyana",
  },
  {
    vname: "Honda City 2024",
    vtype:"bike",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"Honda City 2024 is a popular mid-size sedan known for its stylish design, comfortable interiors, and advanced technological features. It's miileage is 16-19 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse1.mm.bing.net/th?id=OIP.3OC9JF3x9EV3q6HOSfaxgAHaE8&pid=Api&P=0&h=180",
    },
    cost: 1200,
    location: "Cotswolds",
    city:"Lucknow",
    state: "Jharkhand",
  },
  {
    vname: "Tata Safari 2024",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"120",
    vpower:"1200",
    vinfo:"The Tata Safari is a flagship SUV from Tata Motors, known for its bold design, powerful performance, and spacious interiors. It's mileage is 15-18 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse3.mm.bing.net/th?id=OIP.NZEV4Ez0HJT-xKOPM2QZVQHaE8&pid=Api&P=0&h=180",
    },
    cost: 2200,
    location: "WEC near Internatinal Park, 274403",
    city:"Lucknow",
    state: "Karnatka",
  },
  {
    vname: "Kawasaki Ninja ZX10R",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"200",
    vpower:"1200",
    vinfo:"The Ninja lineup is highly regarded among motorcycle enthusiasts for its speed, handling capabilities, and aggressive design. It's mileage is arounnd 10-11 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse2.mm.bing.net/th?id=OIP.TJ4HNJE7KmCyeMkDMX8uzAHaEK&pid=Api&P=0&h=180",
    },
    cost: 1800,
    location: "KKK Chawni Station, Agra 282001",
    city:"Lucknow",
    state: "Kerla",
    
  },
  {
    vname: "Mahindra Scorpio-N 2024",
    vtype:"Mannual",
    vfuel:"Deisel",
    vlimit:"150",
    vpower:"1200",
    vinfo:"The Mahindra Scorpio N is a powerful and rugged SUV that has made a significant impact in the Indian automotive market since its launch. It's diesel-mannual engine mileage around 14-18kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse1.mm.bing.net/th?id=OIP.aGqji319sPkPqckYTF8S-wHaE8&pid=Api&P=0&h=180",
    },
    cost: 1500,
    location: "XZX  near Central Jail, Jagga Colony, 110001",
    city:"Lucknow",
    state: "Maharastra",
    vtype:"car",
  },
  {
    vname: "Nexon",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"140",
    vpower:"1200",
    vinfo:"To abRoof rails, cladding, and a compact footprint make it suitable for both urban and off-road driving.It's mileage arround 14-19kmpl",
    image:{
      filename: "Listingimage",
      url: "https://thumbs.dreamstime.com/b/new-tata-nexon-chandrapur-india-167246205.jpg",
    },
    cost: 1600,
    location: "Safedabad, near bank of india 251210",
    city:"Lucknow",
    state: "Tamilnadu",
    
  },
  {
    vname: "Audi",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"120",
    vpower:"1200",
    vinfo:"Advanced driver assistance systems including lane keep assist, adaptive cruise control, and parking assist.It's mileage arround 16-18kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse4.mm.bing.net/th?id=OIP.XZzdOerGuE8M8NYPG7wvQgHaEK&pid=Api&P=0&h=180",
    },
    cost: 4000,
    location: "lucknow Near Tedi Pulia 223001",
    city:"Lucknow",
    state: "UP",
    
  },
  {
    vname: "Rollys Royce",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"180",
    vpower:"1200",
    vinfo:"Rolls-Royce is synonymous with luxury, craftsmanship, and exclusivity in the automotive world. It's mileage is around 7-9 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse1.mm.bing.net/th?id=OIP.x0I3gbowtw65ejuPQdQPAQHaEK&pid=Api&P=0&h=180",
    },
    cost: 4000,
    location: "TTT near AIIMS, 273001",
    city:"Lucknow",
    state: "Delhi",
    
  },
  {
    vname: "Hyundai Verna 2023",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"110",
    vpower:"1200",
    vinfo:"It has been a key player in the sedan market in India and around the world, offering a blend of comfort, technology, and efficiency. It's mileage is around 17-25 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://www.financialexpress.com/wp-content/uploads/2023/03/2023-Hyundai-Verna-Review-1.jpg",
    },
    cost: 5000,
    location: "CVC near Shivam Restaurant, 110093",
    city:"Lucknow",
    state: "Mumbai",
    
  },
  {
    vname: "Maruti Suzuki WagnoR",
    vtype:"car",
    vfuel:"Deisel",
    vlimit:"150",
    vpower:"1200",
    vinfo:"Tothe Wagon R has been a favorite among urban commuters and small families for several decades. It's mileage is around 20-25 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse4.mm.bing.net/th?id=OIP.AyO50AEul3c-j29rTl-3GAHaE8&pid=Api&P=0&h=180",
    },
    cost: 1100,
    location: "JKJ near Shiv Temple, 212011",
    city:"Meerut",
    state: "Goa",
  },
  {
    vname: "Royal Enfield hunter 350",
    vtype:"car",
    vfuel:"Petrol",
    vlimit:"120",
    vpower:"1200",
    vinfo:"The Hunter 350 is powered by a 349cc single-cylinder engine, delivering around 20 horsepower. It's mileage is around 33-38 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse2.mm.bing.net/th?id=OIP.rGBxSQZfV_S3J4waIF8m0wHaHa&pid=Api&P=0&h=180",
    },
    cost: 2500,
    location: "UUU near Bus Stand, Laxamana Colony 224123",
    city:"Lucknow",
    state: "Manipur",
  },
  {
    vname: "Bajaj Platina 100cc",
    vtype:"bike",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"The Platina series typically features a 100cc or 110cc single-cylinder engine, providing decent power for city riding while maintaining excellent fuel economy. It's mileage is around 70-75 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse4.mm.bing.net/th?id=OIP.GC9WuhsJTBAODgij1aMD6wHaFj&pid=Api&P=0&h=180",
    },
    cost: 750,
    location: "JIJ near Creamation Centre, Abdul Colony 250001",
    city:"Lucknow",
    state: "Tripura",
    
  },
  {
    vname: "Mahindra Bolero",
    vtype:"bike",
    vfuel:"Deisel",
    vlimit:"100",
    vpower:"1200",
    vinfo:"It typically comes with a 1.5-liter mHawk diesel engine that delivers around 75 horsepower and 210 Nm of torque. It's mileage is around 15-20 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse2.mm.bing.net/th?id=OIP.Vafj9IqKI8SmMz75aDyxnwHaEK&pid=Api&P=0&h=180",
    },
    cost: 1600,
    location: "LKL near shadab hospital, 262701",
    city:"Lucknow",
    state: "Mijoram",
    
  },
  {
    vname: "Mahindra XUV700",
    vtype:"bike",
    vfuel:"Petrol",
    vlimit:"130",
    vpower:"1200",
    vinfo:"The XUV700 features a modern and bold design with a wide stance, sleek LED headlights, and a prominent grille.  It's mileage is around 12-15 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse1.mm.bing.net/th?id=OIP.D2DY2Ew0L-gwMtfqC0MMigHaEK&pid=Api&P=0&h=180",
    },
    cost: 2000,
    location: "UIU palari chauraha, 225001",
    city:"Lucknow",
    state: "Sikkim",
    
  },
  {
    vname: "Tata Curvv",
    vtype:"bike",
    vfuel:"Electric",
    vlimit:"90",
    vpower:"1200",
    vinfo:"The Curvv features a coupe-like silhouette with a sleek, aerodynamic profile. It has sharp lines, a prominent front grille, and LED headlights with DRLs (Daytime Running Lights). It's mileage is around 1-15 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse1.mm.bing.net/th?id=OIP.0GXXMMO_FN28KZ7HISfrhAHaE8&pid=Api&P=0&h=180",
    },
    cost: 1200,
    location: "CFC near Mahatma Gandhi Park, 241001",
    city:"Lucknow",
    state: "Pondicheri",
  },
  {
    vname: "Skoda Slavia",
    vtype:"bike",
    vfuel:"Petrol",
    vlimit:"110",
    vpower:"1200",
    vinfo:"The Slavia not only looks good but offers a thrilling driving experience, be it in the city or highway, due to its peppy engines and good handling. There's ample comfort. It's mileage is 15-20 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse2.mm.bing.net/th?id=OIP.62pY4HttxdjZUx0L7VE87QHaEA&pid=Api&P=0&h=180",
    },
    cost: 6000,
    location: "YUY near mohan lawn, 246701",
    city:"Lucknow",
    state: "Meghalay",
  },
  {
    vname: "Renault Kiger",
    vtype:"bike",
    vfuel:"Deisel",
    vlimit:"100",
    vpower:"1200",
    vinfo:"The price of Renault Kiger, a 5 seater Compact SUV, ranges from Rs. 6.00 - 11.23 Lakh. It is available in 23 variants, with an engine of 999 cc and a choice of 2 transmissions. It's mileage is around 17-21 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://wallpapers-all.com/uploads/posts/2021-12/2_renault_kiger.jpg",
    },
    cost: 4000,
    location: "IUI near rohan restaurant, Bikumpur road, Deoria 274408 ",
    city:"Lucknow",
    state: "Uttarakhnd",
   
  },
  {
    vname: "Mercedes-Benz G-Class",
    vtype:"bike",
    vfuel:"Petrol",
    vlimit:"100",
    vpower:"1200",
    vinfo:"The G-Class, despite its price, is not just for show. It offers powerful driving with great steering, speed, and braking. It's comfortable even on rough roads, inviting you to explore. It's milaege is around 5-7 kmpl",
    image:{
      filename: "Listingimage",
      url: "https://tse1.mm.bing.net/th?id=OIP.EqjnlH8wrsvtVNnZl4LhwAHaE8&pid=Api&P=0&h=180",
    },
    cost: 1800,
    location: "WQW near eye hospital, 260001",
    city:"Lucknow",
    state: "Jammu and Kasmir",
    
  },
];

 module.exports = { data: sampleListings };